#!/bin/bash

x1=512
if [ "$4" != "" ]; then x1=$4; fi
x2=2000
if [ "$5" != "" ]; then x2=$5; fi
x3=-1
if [ "$6" != "" ]; then x3=$6 ; fi

f=$1
cp $f out
for i in $(seq $2 $3); do 
	gia-ast-meta $f $i $x1 $x2 $x3 -a > _out && \
		echo -n "Content of _out : " && cat _out && \
		r=$(cat _out | awk '/feh/ { print $2}') && \
		c=$(cat _out | awk '/port/ { print $2}') && \
		echo "Montage using : $c and $r" && \
		$binroot/composite_content_result.sh $c $r  && \
		rm _out && \
		cp $r out && \
		echo "Composite Done" || echo "Something failed for iteration $i"
done
