#!/bin/bash
. .env &>/dev/null

mkdir -p out
astcmd=gia-ast
devrepopath=$srcroot/x__etch-a-sketch__210224/gia-ast
if [ "$astusemetasvr" == "true" ] ; then 
	astcmd=gia-ast-meta  
	echo "Using Meta Service"
	devcmd=$devrepopath/gia-ast-meta.js
	if [ "$devmode" == "true" ] ; then
		astcmd=$devcmd
		echo "Using Dev script: $astcmd"
	fi
	sleep 1
else 
       devcmd=$devrepopath/gia-ast.js
        if [ "$devmode" == "true" ] ; then
                astcmd=$devcmd
                echo "Using Dev script: $astcmd"
        fi

fi

compositeresultcmd=$binroot/composite_content_result.sh
cmdecho=""
if [ "$echocmd" == "true" ] ; then 
	astcmd="echo $astcmd"  
	compositeresultcmd="echo $compositeresultcmd"
	cmdecho="echo "
fi

x1=512
if [ "$4" != "" ]; then x1=$4; fi
x2=2000
if [ "$5" != "" ]; then x2=$5; fi
x3=-1
if [ "$6" != "" ]; then x3=$6 ; fi

f=$1

if [ "$1" == "" ]; then
	echo "Usage: $0 <file> <startport> <endport> [resolution 1] [resolution 2] [resolution 3]"
else
#echo "$0 $1 $2 $3 $4 $5 $6 $7"

#echo $compositeresultcmd $c $r  

cp $f out
for i in $(seq $2 $3); do 
 		$astcmd $f $i $x1 $x2 $x3 -a > _out && \
		echo -n "Content of _out : " && cat _out && \
		export r=$(cat _out | awk '/feh/ { print $2}') && \
		export c=$(cat _out | awk '/port/ { print $2}') && \
	  $compositeresultcmd $c $r  && \
		$cmdecho rm _out && \
		$cmdecho cp $r out && \
		echo "Composite Done" || echo "Something failed for iteration $i"
done

fi
