#!/bin/bash
#@STCGoal A Docker image is build with the builder username and pushed to the same repo
useremail="jgi@jgwill.com"

. _env.sh && [ "$dockertag" != "" ] && \
if [ "$(uname -s)" == "Linux" ]; then echo "Creating User based image"
	_cuser=$(whoami)
	_uid=$UID
	dockertaguser=$dockertag"-"$_cuser
	cdir="$(pwd)"
	wdir="$cdir/build_user__"$(tlid)
	if [ -e "$wdir" ] ; then echo "Hum... $wdir exist already"
	else

	mkdir -p $wdir
	DKUSERNAME=$_cuser
	DKUID=$_uid
	_dkusehomedir="WORKDIR /home/$DKUSERNAME"
	_dkuserchg="USER $DKUSERNAME"
	if [ "$dknouserchg" != "" ]; then _dkuserchg="";fi
	if [ "$dkusehomedir" == "" ] ||  [ "$dkusehomedir" == "false" ] ; then _dkusehomedir="";fi
	#
	_gituseremail="RUN git config --global user.email \"$useremail\""
	_gitusername="RUN git config --global user.name \"$DKUSERNAME\""
	cd $wdir && \
		echo "FROM $dockertag" >> Dockerfile && \
		echo "RUN useradd -rm -d /home/$DKUSERNAME -s /bin/bash -g root -G sudo -u $DKUID $DKUSERNAME" >> Dockerfile && \
		echo "$_dkusehomedir " >> Dockerfile && \
		echo "$_dkuserchg "  >> Dockerfile && \
		echo "$_gituseremail " >> Dockerfile && \
		echo "$_gitusername "  >> Dockerfile && \
		echo "Created Dockerfile" && \
		docker build -t $dockertaguser . && docker push $dockertaguser && rm -rf $wdir && echo "Created image : $dockertaguser" && echo "All done and cleanup" || \
			echo "FAILED SOMEWHOW"
		#cp $binroot/templates/Dockerfile-user Dockerfile && \

	fi # done folder did not exist

		#__DOCKERTAG__ DKUSERNAME  DKUID




	

else
	echo "Please run this on linux or upgrade to run using WSL"
fi || \
		echo "Please create _env.sh or be somewhere where these is that ;) and define dockertag"
