#!/bin/bash



. _env.sh &> /dev/null || . .env &> /dev/null


if [ "$containername" == "" ]; then
	echo "Please define \$containername in .env or _env.sh"
else
	cmd=bash
	if [ "$1" != "" ]; then cmd="$1";fi

	echo "Running bash to Container/docker name : $containername"
	docker exec -it $containername $cmd




fi
