#!/bin/bash


tst=$(uname)

if [ "$tst" == "Linux" ] ; then 
	if [ "$1" == "" ]; then
	docker inspect -f '{{.Name}} - {{.NetworkSettings.IPAddress }}' $(docker ps -aq)
else 
	docker inspect -f '{{.Name}} - {{.NetworkSettings.IPAddress }}' $(docker ps -aq)| awk '/'$1'/ { print $3 }'
	fi
else
	echo "Use WSL to run this"
fi

