#!/bin/bash


(. .env &> /dev/null  && . _env.sh &> /dev/null ) || (. .env &> /dev/null || . _env.sh &> /dev/null)


if [ "$dockertag" == "" ] ; then
	export dockertag="$containertag"
fi

if [ "$dockertag" == "" ] ; then 
	echo "Please define dockertag in .env or _env.sh"
else
	docker push $dockertag
fi
