#!/bin/bash


export goon=0
if [ -f ".env" ] && [ -f "_env.sh" ]; then
	        . _env.sh && . .env && goon=1
	else
		. .env &> /dev/null || . _env.sh &> /dev/null

fi

if [ "$dockertag" == "" ] ; then
	export dockertag="$containertag"
fi

if [ "$dockertag" == "" ] ; then 
	echo "Please define dockertag in .env or _env.sh"
else
	docker push $dockertag
fi
