#!/bin/bash

(. .env &> /dev/null || . _env.sh &> /dev/null)\
docker run -it --rm \
	-v $(pwd):/work \
	-v $binroot:/a/bin \
	-e DISPLAY=$DISPLAY \
	$dockertag $1 \
	 || echo "Please define dockertag in .env"

