#!/bin/bash
goon=1
. .env &> /dev/null || . _env.sh &> /dev/null || goon=0

if [ "$goon" == 1 ]; then
	dknamearg="--name $containername"
	if [ "$containername" == "" ]; then
		dknamearg=""
	fi
export pwdmountpath=/work
if [ "$custompwdmountpath" == "" ] ; then echo "No special mount path"
else
	pwdmountpath=$custompwdmountpath
fi
echo "Running container : $dockertag $dknamearg"
docker run -it --rm $dknamearg $dkextra \
	-v $(pwd):/$pwdmountpath \
	-v $binroot:/a/bin \
	-e DISPLAY=$DISPLAY \
	$dockertag $1 
else	
echo "Please define dockertag in .env"
fi
