#!/bin/bash


if [ "$1" == "" ] ; then 
	echo "Usage $0 <ext>"
else
	ext="$1"
for f in *.$ext; do 
#filename=$(basename -- "$f")
	if [ -f "$f" ]; then 
		extension="${f##*.}"
		lext=$(echo $extension | tr '[:upper:]' '[:lower:]')
		filename="${f%.*}"
		nfn="$filename.$lext"
		tmpfn="/tmp/$nfn"
		echo "mv $f $tmpfn"
		echo "mv $tmpfn $nfn"
	fi
	#sleep 5 #for dropbox stuff
done


fi

