#!/bin/bash
if [ ! -e "/a/.flag" ];then 
	echo "/a Does not seem to me mounted, mounting it..."
	if [ "$sysuname" == "Linux" ];then 
		sudo mount -t drvfs a: /mnt/a  && echo "/a Mounted" || echo "Error mouting /a"
	else
		echo "OS in not WSL/Linux, can not do much"
	fi
fi

export hostdns=localhost
#export TZ="America/New_York"
export rwroot=$srcroot/rwml__adaptive_style_transfer
shopt -s direxpand

#export zeusdata="/mnt/c/Caishen/Caishen/src/Caishen/Databases/SpiderDbDatabase/gia-mssql/data"
export zeuzdata="/mnt/c/var/lib/mssql/data"

export sysdrive="/c"
export AppSuiteName="Caishen"
if [ "$sysuname" == "" ];then  export sysuname="$(uname)";fi
if [ "$sysuname" == "Linux" ];then export sysdrive="/mnt/c";fi #different mount point on WSL
export WINHOMEROOT=$sysdrive/Users
export WINUSER=jeang
export USERWINHOME=$WINHOMEROOT/$WINUSER

export AppSuiteRootPath=$USERWINHOME/AppData/Local/$AppSuiteName
export AppSuiteConfigRootPath=$AppSuiteRootPath/config
export AppSuiteDataRootPath=$AppSuiteRootPath/data
export DataCsvRepoRelativePath=$caishenroot/src/Caishen/PDSP/DataCsv 

#StrategyRunner requires access to a folder where we store up to date strategies
#CaishenSolutionDir
export CaishenStrategyRunnerLib=$CaishenSolutionDir/Lib
# Relative to working and latest
export ailatesttag=sc220807



